version: "2"
services:
        
  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image : jaegertracing/all-in-one:latest
    restart: unless-stopped
    ports:
      #- 4317:4317 # OLTP/gRPC
      - 5775:5775/udp
      - 6831:6831/udp # Compact transport
      - 6832:6832/udp # jaeger.thrift 
      - 16686:16686 # /api endpoint
      - 14250:14250 #gRPC Transport
      - 14268:14268 #HTTP Transport
      - 14269:14269 # Jaeger Health Check
      - 55681:55681 # OLTP/HTTP
      - 9411:9411
    #environment:
    #  - SPAN_STORAGE_TYPE=elasticsearch
    #  - ES_SERVER_URLS=http://elasticsearch:9200

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    networks:
      - elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: on-failure
    environment:
      - cluster.name=jaeger-cluster
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data      

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic
    
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./output:/etc/output:rw
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver
    depends_on:
      - jaeger-all-in-one
 
volumes:
  esdata:
    driver: local

networks:
  elastic:
    driver: bridge 