receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
  
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  logging:

  #zipkin:
  #  endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
  #  format: proto
  
  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true
  
  file:
    path: /etc/output/logs.json

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [logging, file]